### ISSUE TITLE
make menuconfig 不正常

### ISSUE THREAD

**Issue by xiegongsheldon** [icplus/mtk7628_eCos#1]
xsc@ubuntu:~/mtk7628_eCos$ make menuconfig
make -C ra305x_ap_adv menuconfig
make[1]: Entering directory '/home/xsc/mtk7628_eCos/ra305x_ap_adv'
make -C ra305x_router menuconfig
make[2]: Entering directory '/home/xsc/mtk7628_eCos/ra305x_ap_adv/ra305x_router'
/bin/sh: 1: cd: can't cd to ../ra305x_bsp/install
/bin/sh: 1: dos2unix: not found
/bin/sh: 1: cd: can't cd to ../ra305x_bsp/install
chmod u+rx scripts/lxdialog/lxdialog
chmod u+rx scripts/imghdr/imghdr
chmod u+rx scripts/imghdr/imghdr_bn
chmod u+rx scripts/imghdr/cookie
bash scripts/Menuconfig config.in
Using defaults found in .config
Preparing scripts: functions, parsing.......done.
停在这边不动了

**Comment by luojasonlee** [comment]
64-bit systems install 32-bit libraries

apt-get install lib32ncurses5 ​
apt-get install lib32z1

**Comment by xiegongsheldon** [comment]
thank you
